websol/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
path('admin/', admin.site.urls),
path('',include('app.url')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User,auth
# Create your models here.

class Userdetails(User):
    user=models.OneToOneField(User,parent_link=True,primary_key=True,on_delete=models.CASCADE)
    address=models.CharField(max_length=1000)
    phone=models.IntegerField(default=0)
    image=models.ImageField(upload_to="gallery",null=True)
    def __str__(self):
        return self.user.username


class category(models.Model):
    name=models.CharField(max_length=100)
    price=models.IntegerField(default=0)
    slug=models.CharField(max_length=100,null=True,unique=True)
    image=models.ImageField(upload_to="gallery")
    offer=models.IntegerField(null=False,default=0)
    
    
    def __str__(self):
        return self.name
class video(models.Model):
    select_course=models.ForeignKey(category,on_delete=models.CASCADE)
    tittle=models.CharField(max_length=200)
    serial_num=models.IntegerField(null=False)
    video_id=models.FileField(null=True)

    def __str__(self):
        return str(self.serial_num)
class Test(models.Model):
    user=models.ForeignKey(Userdetails,on_delete=models.CASCADE)
    test=models.FileField(upload_to="file")
    test_name=models.CharField(max_length=200)
    
    def __str__(self) :
        return self.test_name
    
class Certificate(models.Model):
    user=models.ForeignKey(User,null=False,on_delete=models.CASCADE)
    certificate=models.ImageField(upload_to="gallery")
    def __str__(self):
        return self.user.username



class Usercourse(models.Model):
    user=models.ForeignKey(User,null=False,on_delete=models.CASCADE)
    select_course=models.ForeignKey(category,null=False,on_delete=models.CASCADE)
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.user.username} - {self.select_course.name}'

class Payment(models.Model):
    order_id=models.CharField(max_length=100,null=False)        
    payment_id=models.CharField(max_length=100,null=True)
    user_course=models.ForeignKey(Usercourse,on_delete=models.CASCADE,null=True,blank=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    course=models.ForeignKey(category,on_delete=models.CASCADE)
    date=models.DateTimeField(auto_now_add=True)
    status=models.BooleanField(default=False)        
class Testsoulution(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)        
    doc=models.FileField(upload_to="file")
    def __str__(self) -> str:
        return self.user.username + "--" + self.user.email

templates/accounts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    account
</body>
</html>

templates/certificate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        .my1{
            height: 700px;
            width: 100%;
            background-color: rgb(24, 110, 77);
        }
        .my2{
           
            width: 100%;
            background-color: rgb(219, 219, 219);
        
            border-radius: 30px;
        }

        .my2:hover{
            background-color: rgb(214, 236, 15);
          
        }
    </style>
</head>
<body>
    {% include 'includes/header.html' %}
<section class="my1">

   <div>  <h1 style="text-align: center; text-shadow: 2px 4px 6px rgba(6, 7, 3, 0.514); color: cornsilk">JOINUS</h1></div>
   <hr>
   <br><br> <div>  <h1 style="text-align: center; text-shadow: 2px 4px 6px  rgba(6, 7, 3, 0.514); color: cornsilk">AFTER COURSE COMPLETION YOU WILL DOWNLOAD YOUR CERTIFICATE HERE</h1></div>
   <br><br><br>
   <br>

<div class="row">
    {% for i in certificate %}
    <div class="col-md-12"><div class="my2"><strong><h2 style="text-shadow:2px 4px 6px rgb(241, 128, 22); padding: 5px; text-align: center;"><a href="{{i.certificate.url}}" style="text-decoration: none;">DOWNLOAD CERTIFICATE</a> </h2></strong></div></div>
{% endfor %}
    

</div>

    </div>
</section>
<br><br>
{% include 'includes/footer.html' %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

templates/check.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- <link rel="stylesheet" href="cssfiles/style.css">
    <link rel="stylesheet" href="cssfiles/utility.css">
    <link rel="stylesheet" href="cssfiles/owl.carousel.css">
    <link rel="stylesheet" href="cssfiles/owl.theme.green.css">
    <script src="jsfiles/jquery.min.js"></script>
    <script src="jsfiles/owl.carousel.min.js"></script> -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">


</head>

<body>
    <section>
       {% include 'includes/header.html' %}
    </section>
    <div class="modal" tabindex="-1">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Modal title</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
      </div>
    <!--  -->
    <!-- {% if order is not None %}
    <h6>{{order}}</h6>
    <h3>{{payment}}</h3>
    {% endif %} -->


    <section class="container">

        <div class="row " style="background-color:ghostwhite;   box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);;">
            <div class="col-md-6  ">
                <div style="padding: 5px;"><img height="450PX" width="100%" src="{{cour.image.url}}" alt=""></div>
            </div>
            <div class="col-md-6  ">
                <div style="padding: 5px;">
                   <H1 style="text-align: center; color: black;
                  ">{{cour.name}}</H1>
                   <HR></HR>
                   <h2>price:₹{{cour.price}}</h2>
                   <h2>offer:{{cour.offer}}%</h2>
                  <!-- <h3 style=" color: black;">Payble Amount : <strong>{{cour.video.}}</strong></h3> -->
                </div>

                <div  style="margin-top: 15px;">  <a href="?action=create_payment"   ><button type="button" class=" btn " style=" background-color: rgb(229, 234, 234);font-size: 20px;padding: 15px; ">Pay Now</button> </a></div>
            </div>
        </div>


    </section>






    











  





    {% include 'includes/footer.html' %}

    {% if order is not None %}
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
        var options = {
            "key": "rzp_test_TZMz05AomJrJ17", // Enter the Key ID generated from the Dashboard
            "name": "WEBSOL",
            "amount":"{{order.amount}}",
            "description": "payment for {{order.id}}",
            "image": "https://example.com/your_logo",
            "order_id": "{{order.id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
            "callback_url": "http://127.0.0.1:8000/verify_payment",
            "prefill": {
                "name": "{{profile.user.first_name}}",
                "email": "{{profile.email}}",
                "contact": "{{profile.phone_no}}"
            },
            "theme": {
                "color": "#3399cc"
            }
        };
        var rzp1 = new Razorpay(options);
        rzp1.open();
    </script>
      {% endif %}
{% if error is not None %}
<script>
window.onload=()=>{
    alert("{{error}}")
}
</script>
{% endif %}
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>

</body>

</html>

templates/display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <iframe src="{{video.video_url}}/preview" frameborder="0" style="width: 500px;height: 500px;"></iframe>

    <section>
        {% for video in a.video_set.all %}
        <a href="?lecture={{video.serial_num}}">{{video.tittle}}</a>
        {% endfor %}
    </section>
</body>
</html>

templates/editprofile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'cssfiles/style.css' %}">
    <link rel="stylesheet" href="{% static 'cssfiles/utility.css' %}">
    <link rel="stylesheet" href="{% static 'cssfiles/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'cssfiles/owl.theme.green.css' %}">
    <script src="{% static 'jsfiles/jquery.min.js' %}"></script>
    <script src="{% static 'jsfiles/owl.carousel.min.js' %}"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <section>
        {% include 'includes/header.html' %}
    </section><hr>
    
    <section class="container">
        <form action="{% url 'edit' %}" method="post">
            {% csrf_token %}
        <div class="row " style="background-color: gainsboro;box-shadow: 2px 4px 8px black;">
           
            <div class="col-md-12 ">
                <div style="padding: 20px;">
                  
                        <!-- 2 column grid layout with text inputs for the first and last names -->
                        <div class="row mb-4">
                          <div class="col">
                            <div class="form-outline">
                              <input type="text" id="form6Example1" class="form-control" name="firstname" />
                              <label class="form-label" for="form6Example1">First name</label>
                            </div>
                          </div>
                          <div class="col">
                            <div class="form-outline">
                              <input type="text" id="form6Example2" class="form-control" name="lastname" />
                              <label class="form-label" for="form6Example2">Last name</label>
                            </div>
                          </div>
                        </div>
                      
                          
                        <!-- Email input -->
                        <div class="form-outline mb-4">
                            <input type="email" id="form6Example5" class="form-control" name="email"/>
                            <label class="form-label" for="form6Example5">Email</label>
                          </div>
                     
                      
                           <!-- Number input -->
                        <div class="form-outline mb-4">
                            <input type="number" id="form6Example6" class="form-control" name="phone"/>
                            <label class="form-label" for="form6Example6">Phone</label>
                          </div>


                        <!-- Text input -->
                        <div class="form-outline mb-4">
                          <input type="text" id="form6Example4" class="form-control" name="address"/>
                          <label class="form-label" for="form6Example4">Address</label>
                        </div>
                  
                      
                       
                      
                        <!-- Message input -->
                      
                     
                      
                        <!-- Submit button -->
                        <button type="submit" class="btn btn-primary btn-block mb-4">submit</button>
                      </form>
                </div>
            </div>
        </div>


    </section>
<br><br>
    {% include 'includes/footer.html' %}
</body><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
crossorigin="anonymous"></script>

</html>

templates/form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'cssfiles/form.css' %}">
</head>

<body>
    {% include 'includes/header.html' %}
    <section class="container">
        <div class="row justify-content-center  " style="align-items: center;">
            <div class="col-md-5 m-2 p-4">
                <div class="ff" >  <div class="m2">
                    <div >
                        <h3 style="font-size: 45px;font-weight: 400;" >LOGIN</h3>
                        <p style="font-size: 20px;color: blue;font-weight: 600;">joinus</p>
                    </div>
                    <div >
                        <form  action="{% url 'form' %}" method="post" onsubmit="return myvalidation()">
                            {% csrf_token %}
                            <div style="margin-bottom: 10px;"><label for="">Username</label><br>
                                <input class="f1"  type="text" name="username" id="a1">
                                <p id="s1"  class="f2" ></p>
                            </div>
                            <!-- <div style="margin-bottom: 10px;"><label for="">Mobile number</label><br>
                                <input class="f1" type="number" name="" id="a2">
                                <p id="s2"class="f2" ></p>
                            </div> -->
                            <div style="margin-bottom: 10px;"><label for="">PASSWORD</label><br>
                                <input
                                class="f1"  style=" background-color: rgba(0, 0, 255, 0.087);"
                                    type="password" name="password" id="a2">
                                <p id="n2" class="f2" ></p>password must be atleast 6 character
                                
                            </div>
                            <!-- <div style="margin-bottom: 10px;"><label for="">Email (optional)</label><br>
                                <input class="f1" type="email" name="" id="a4">
                                <p id="s4"></p>
                            </div> -->
                            <div style="margin-bottom: 30px;">
                                
                            
                            </div>
                            <div style="margin-bottom: 30px;"> <input type="submit" name="" id="" value="continue" class="f4" >
                            </div>
                            <div>
                                <p>
                                    create account? <a class="w1"
                                        style="text-decoration:none ;color: rgba(0, 0, 255, 0.806);" href="{% url 'signup' %}">Sign up</a> <br>
                                  
                                </p>
                               
                            </div>
                        </form>
                    </div>
                </div></div>
            </div>
        </div>
    </section><br><br>
    {% include 'includes/footer.html' %}

    <script>


        function myvalidation() {
            var a = document.getElementById("a1").value;
            var b = document.getElementById("a2").value;
            var passw=/^(?=.\d)(?=.[a-z])(?=.*[A-Z]).{6,20}$/;
            


            if (a == 0 || a == "") {
                document.getElementById("s1").innerHTML = "please enter these filled"
                return false;
            }
            else if (a.length < 8) {
                document.getElementById("s1").innerHTML = "atleast minimum 8 words type"
                return false;
            }

            else if (a.length > 16) {
                document.getElementById("s1").innerHTML = "atleast maximum 16 words type"
                return false;
            }
            else if (b == null || b == "") {

                document.getElementById("n2").innerHTML = "please filled these filled";
                return false;

                }
            if (b.match (passw)) {


                document, getElementById("n2").innerHTML = "atleat minimum eight character in password"
                return true;

                }
            // else {
            //     document.getElementById("d1").innerHTML = a;
            //     document.getElementById("d2").innerHTML = b;
            //     document.getElementById("d3").innerHTML = c;
            //     document.getElementById("d4").innerHTML = d;
            //     return false;
            // }

        }



    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>

</html>

templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>password reset</h1>
    <h3>Password reset</h3>

<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Send email">
	
</form>
</body>
</html>

templates/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>enter your new password</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit">done</button>
    </form>
</body>
</html>

templates/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    a email has been send please check your mail
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'cssfiles/form.css' %}">
</head>

<body>
    {% include 'includes/header.html' %}
    {% if messages %}
    {% for message in messages %}
        
<script>
    window.alert("{{message}}")
  </script>
        <h1></h1>

        <!-- alert("{{message}}") -->
        {% endfor %}
    
    {% endif %}
    <section class="container">
        <div class="row justify-content-center  " style="align-items: center;">
            <div class="col-md-5 m-2 p-4">
                <div class="ff" >  <div class="m2">
                    <div >
                        <h3 style="font-size: 45px;font-weight: 400;" >SIGN UP</h3>
                        <p style="font-size: 20px;color: blue;font-weight: 600;">joinus</p>
                    </div>
                    <div >
                        <form  action="{% url 'signup' %}" method="post" onsubmit="return myvalidation()"  >
                            {% csrf_token %}
                            <div style="margin-bottom: 10px;"><label for="">Firstname</label><br>
                                <input class="f1"  type="text" name="f_name" id="g1">
                                <p id="s2"  class="f2" ></p>
                            </div>
                            <div style="margin-bottom: 10px;"><label for="">Lastname</label><br>
                                <input class="f1"  type="text" name="l_name" id="g2">
                                <p id="s3"  class="f2" ></p>
                            </div>
                            <div style="margin-bottom: 10px;"><label for="">Email</label><br>
                                <input class="f1"  type="email" name="email" id="">
                                <p id=""  class="f2" ></p>
                            </div>

                            <div style="margin-bottom: 10px;"><label for="">username</label><br>
                                <input class="f1"  type="text" name="username" id="a4">
                                <p id="s4"  class="f2" ></p>
                            </div>
                           
                            <div style="margin-bottom: 10px;"><label for="">PASSWORD</label><br>
                                <input
                                class="f1"  style=" background-color: rgba(0, 0, 255, 0.087);"
                                    type="password" name="password" id="g3">
                                <p id="s6" class="f2" ></p>
                                <!-- <p style="font-size:10px ;">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                        style="color:blue ;padding-top:5px" fill="currentColor" class="bi bi-exclamation-lg"
                                        viewBox="0 0 16 16">
                                        <path
                                            d="M7.005 3.1a1 1 0 1 1 1.99 0l-.388 6.35a.61.61 0 0 1-1.214 0L7.005 3.1ZM7 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0Z" />
                                    </svg> 
                                </p> -->
                            </div>
                            <div style="margin-bottom: 10px;"><label for="">Phone</label><br>
                                <input class="f1"  type="tel" name="phone" id="g2">
                                <p id="s5"  class="f2" ></p>
                            </div>
                            <div style="margin-bottom: 30px;">
                                <!-- <P>By enrolling your mobile phone number, you consent to receive automated security
                                    notifications via text message from Amazon. Message and data rates may apply. -->
                                </P>
                            </div>
                            <div style="margin-bottom: 30px;"> <input type="submit" name="" id="" value="continue" class="f4" >
                            </div>
                            <div>
                                <p>
                                    Already have an account? <a class="w1"
                                        style="text-decoration:none ;color: rgba(0, 0, 255, 0.806);" href="{% url 'form' %}">Log in</a> <br>
                                     <br>
                                </p>
                                
                            </div>
                        </form>
                    </div>
                </div></div>
            </div>
        </div>
    </section><br><br>
    {% include 'includes/footer.html' %}


    <script>


        function myvalidation() {
            var b=document.getElementById("g1").value;
            var c=document.getElementById("g2").value;
            var a = document.getElementById("a4").value;
            var d = document.getElementById("g2").value;
            var e = document.getElementById("g3").value;
            var pass=/^(?=.\d)(?=.[a-z])(?=.*[A-Z]).{6,20}$/;
           
            if (b==0||b=="" ){
                document.getElementById("s2").innerHTML = "please enter these filled"
                return false;
            }
            if (c==0||c=="" ){
                document.getElementById("s3").innerHTML = "please enter these filled"
                return false;
            }

            if (a == 0 || a == "") {
                document.getElementById("s4").innerHTML = "please enter these filled"
                return false;
            }
            else if (a.length < 8) {
                document.getElementById("s4").innerHTML = "atleast minimum 8 words type"
                return false;
            }

            else if (a.length > 16) {
                document.getElementById("s4").innerHTML = "atleast maximum 16 words type"
                return false;
            }
            if (e.match(pass)){
                document.getElementById("s6").innerHTML="atleast 8 special character type"
                return true;
            }
            // if (d.length==10 ){
            //     document.getElementById("s5").innerHTML = "please enter 10 digits"
            //     return false;
            // }
            
            
            // else {
            //     document.getElementById("d1").innerHTML = a;
            //     document.getElementById("d2").innerHTML = b;
            //     document.getElementById("d3").innerHTML = c;
            //     document.getElementById("d4").innerHTML = d;
            //     return false;
            // }

        }



    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>

</html>

templates/tax.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    tax
</body>
</html>

templates/v2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Welcome to learning</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% for i in v %}
              <li class="nav-item">
                <h1><a class="nav-link active" aria-current="page" href="{{i.video_url}}">{{i.tittle}}</a></h1>
              </li>
              {% endfor %}              
          </div>
        </div>
      </nav>
</body>
</html>